{% set name = "bacon" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Canop/bacon/archive/v{{ version }}.tar.gz
  sha256: 640a6a76213ef4b7337c7a3495afba3056ee5d58b3b7aefebe35edfc9c179e16

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - bacon --help

about:
  home: https://github.com/Canop/bacon
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: background rust code check
  dev_url: https://github.com/Canop/bacon

extra:
  recipe-maintainers:
    - danielnachun
