{% set name = "bacon" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Canop/bacon/archive/v{{ version }}.tar.gz
  sha256: d8b516b0af8564fbd470513bd6420ba077e74a3860d655efaf9ec12fda47e7a1

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - bacon --help

about:
  home: https://github.com/Canop/bacon
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: background rust code check
  dev_url: https://github.com/Canop/bacon

extra:
  recipe-maintainers:
    - danielnachun
