{% set name = "bacon" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Canop/bacon/archive/v{{ version }}.tar.gz
  sha256: f078f2326da81cab31a3196d4ac43d0771d5679c7d5b32ce38309ff89f80559a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - bacon --help

about:
  home: https://github.com/Canop/bacon
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: background rust code check
  dev_url: https://github.com/Canop/bacon

extra:
  recipe-maintainers:
    - danielnachun
