{% set name = "bacon" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Canop/bacon/archive/v{{ version }}.tar.gz
  sha256: ff2460da9f527f48c899fbf40fb7e2645dc3eb28e04677490d7fbab2bdaf8fea

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - bacon --help

about:
  home: https://github.com/Canop/bacon
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: background rust code check
  dev_url: https://github.com/Canop/bacon

extra:
  recipe-maintainers:
    - danielnachun
