context:
  version: "3.21.0"

package:
  name: bacon
  version: ${{ version }}

source:
  url: https://github.com/Canop/bacon/archive/v${{ version }}.tar.gz
  sha256: 4d258b57976f234547d01ad64e3609e675a5689c28107e74e75bfbede82bf20a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: linux
      then:
        - alsa-lib

tests:
  - script:
      - bacon --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: background rust code check
  homepage: https://github.com/Canop/bacon
  repository: https://github.com/Canop/bacon

extra:
  recipe-maintainers:
    - danielnachun
