context:
  version: "3.9.0"

package:
  name: bacon
  version: ${{ version }}

source:
  url: https://github.com/Canop/bacon/archive/v${{ version }}.tar.gz
  sha256: 64f65248e4be36347611315b3168b015324b137cb35207342dfdc9712051bd83

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - bacon --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: background rust code check
  homepage: https://github.com/Canop/bacon
  repository: https://github.com/Canop/bacon

extra:
  recipe-maintainers:
    - danielnachun
